Config = {}

Config.Blips = {}

Config.RequireItem = true              -- Có yêu cầu item hay không
Config.AnchorItem = "neo_thuyen"      -- Tên item cần để neo
Config.AnchorTime = 4000              -- Thời gian neo (ms)
Config.UnanchorTime = 3000            -- Thời gian gỡ neo (ms)

Config.RemoveDurabilityQuanlity = {
    ["thung_nuoc"] = 5, 
	["lockpick"] = 6, 
	["advancedlockpick"] = 5,
	["bao_thuoc_la"] = 10,
	["lighter"] = 2,
	["cuoc_dao_da"] = 2,
	["cai_phay"] = 2,
	["cay_keo"] = 2,
	["may_xay"] = 2,
	["may_cua"] = 2,
	['pickaxe']	= 10,
	['pickaxe_1'] = 9,
	['pickaxe_2'] = 15,
	['pickaxe_3'] = 20,
	['pickaxe_4'] = 21,
	['gio_hai_dua'] = 10,
}

Config.GiveVehicleRewards = true
Config.Weaponlist = {
	-- Melee
	WEAPON_UNARMED = 1,
	WEAPON_MACHETE = 0,

}

Config.Weapon = {
	{
		WeaponName = "WEAPON_UNARMED",
		WeaponDamage = 0.2,
	},
	{
		WeaponName = "WEAPON_MACHETE",
		WeaponDamage = 0.3,
	},
	{
		WeaponName = "WEAPON_DAGGER",
		WeaponDamage = 0.0,
	},
	{
		WeaponName = "WEAPON_SNIPERRIFLE",
		WeaponDamage = 0.0,
	},
	{
		WeaponName = "WEAPON_BAT",
		WeaponDamage = 0.3,
	},
}

Config.GenderNumbers = {
    ['male'] = 4,
    ['female'] = 5
}
 
Config.PedList = {                                              
	{	--- NHÂN VIÊN LỄ TÂN BỆNH VIỆN
		model = 's_m_m_doctor_01',
		coords = vector4(-550.81, -193.18, 40.45, 211.70),
		gender = 'female',
		animDict = 'amb@world_human_clipboard@male@base',
		animName = 'base',
	},
	{	--- CHECK IN KHÁM BỆNH
		model = 'Bunny_Cute',
		coords = vector4(354.8168, -1419.51, 32.510, 49.79),
		gender = 'female',
		animDict = 'lunyx@iambeauty@p4',
		animName = 'iambeauty@p4',
	},
	{	--- LỄ TÂN CẢNH SÁT Thành phố
		model = 'u_m_m_fibarchitect',
		coords = vector4(441.10, -978.92, 30.69, 184.74),
		gender = 'male',
        animDict = 'anim@amb@nightclub@peds@',
        animName = 'rcmme_amanda1_stand_loop_cop',
	},
	{	--- LỄ TÂN CẢNH SÁT SA MẠC
		model = 'u_m_m_fibarchitect',
		coords = vector4(1720.93, 3625.31, 35.83, 304.32),
		gender = 'male',
        animDict = 'anim@amb@nightclub@peds@',
        animName = 'rcmme_amanda1_stand_loop_cop',
	},
	{	--- CẤP XE
		model = 'u_m_m_fibarchitect',
		coords = vector4(442.05, -1013.51, 28.62, 174.25),
		gender = 'male',
        animDict = 'anim@amb@nightclub@peds@',
        animName = 'rcmme_amanda1_stand_loop_cop',
	},
	{	--- CẤP XE PD Sa mạc
		model = 'u_m_m_fibarchitect',
		coords = vector4(1730.28, 3633.89, 35.88, 302.33),
		gender = 'male',
        animDict = 'anim@amb@nightclub@peds@',
        animName = 'rcmme_amanda1_stand_loop_cop',
	},
	-- {	--- SỬA XE
	-- 	model = 's_m_y_pestcont_01',
	-- 	coords = vector4(436.7645, -1010.90, 29.066, 179.8),
	-- 	gender = 'male',
	-- 	animDict = 'anim@amb@nightclub@peds@',
	-- 	animName = 'rcmme_amanda1_stand_loop_cop',
	-- },
	-- {	---  ĐỘ XE
	-- 	model = 's_m_y_pestcont_01',
	-- 	coords = vector4(433.5760, -1010.82, 29.066, 182.5),
	-- 	gender = 'male',
	-- 	animDict = 'anim@amb@nightclub@peds@',
	-- 	animName = 'rcmme_amanda1_stand_loop_cop',
	-- },
	{	---  CHUỘC XE
		model = 'ig_fbisuit_01',
		coords = vector4(459.04, -1017.06, 28.16, 84.32),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	-- {	---  CHUỘC XE
	-- 	model = 'ig_fbisuit_01',
	-- 	coords = vector4(451.8822, -1004.44, 31.026, 5.843),
	-- 	gender = 'male',
	-- 	scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	-- },
	{	---  CHUỘC XE
		model = 'a_m_m_farmer_01',
		coords = vector4(-2169.04, -519.189, 4.7201, 136.8),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	-- {	---  CHUỘC XE
	-- 	model = 'Bunny_Cute',
	-- 	coords = vector4(-277.144, -919.041, 32.267, 75.96),
	-- 	gender = 'male',
	-- 	scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	-- },
	{	---  CHUỘC XE
		model = 'Bunny_Cute',
		coords = vector4(101.7185, -819.290, 31.317, 340.9),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	{	---  CHUỘC XE
		model = 'Bunny_Cute',
		coords = vector4(-1143.70, -1733.24, 4.5456, 10.60),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	{	---  RÃ XE
		model = 'a_m_m_salton_02',
		coords = vector4(734.1173, -1294.90, 27.036, 92.30),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	-- {	---  TOP THƯƠNG NHÂN
	-- 	model = 'Bunny_Cute',
	-- 	coords = vector4(-228.013, -939.692, 32.246, 71.15),
	-- 	gender = 'male',
	-- 	scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	-- },
	{	---  TOP THƯƠNG NHÂN
		model = 'u_m_o_tramp_01',
		coords = vector4(22.50687, -1217.96, 29.352, 178.4),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{	---  BÁN XE
		model = 'Bunny_Cute',
		coords = vector4(-2237.67, -388.59, 13.52, 323.13),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	{	---  BÁN list XE
		model = 'Bunny_Cute',
		coords = vector4(-2235.29, -390.86, 13.51, 321.18),
		gender = 'male',
		scenario = 'WORLD_HUMAN_CLIPBOARD_FACILITY',
	},
	{	---  TRAO ĐỔI TRANG SỨC
		model = 's_m_y_dealer_01',
		coords = vector4(-683.185, -172.963, 37.821, 307.6),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{
		model = 's_m_y_dealer_01',
		coords = vector4(1495.217, 1115.870, 114.33, 91.37),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{
		model = 's_m_y_dealer_01',
		coords = vector4(-217.540, -2373.14, 26.456, 169.7),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{
		model = 's_m_y_dealer_01',
		coords = vector4(1241.554, -3035.16, 9.3250, 359.9),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{
		model = 's_m_y_dealer_01',
		coords = vector4(465.0748, -1512.68, 34.535, 114.3),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	{
		model = 's_m_y_dockwork_01',
		coords = vector4(-2033.8, -480.46, 11.63, 325.0),
		gender = 'male',
		scenario = 'WORLD_HUMAN_DRUG_DEALER',
	},
	-- { --THUÊ XE 
	-- 	model = 's_m_y_dockwork_01',
	-- 	coords = vector4(-1039.25, -2730.78, 20.21, 240.41),
	-- 	gender = 'male',
	-- 	scenario = 'WORLD_HUMAN_DRUG_DEALER',
	-- },
}

Config.Target = {
    [1] = { --- NHÂN VIÊN LỄ TÂN BỆNH VIỆN
		name = 'le_tan_benh_vien',
		coords = vector3(-550.81, -193.18, 40.45),
		type = 'client',
		event = 'BL_Ambulance:cl:OpenNUI',
		label = 'Trò Chuyện Với Lễ Tân',
		distance = 3.0,
		Job = 'ambulance',
    },
	-- [2] = { --- NHÂN VIÊN LỄ TÊN CẢNH SÁT
	-- 	name = 'le_tan_canh_sat',
	-- 	coords = vector3(1720.93, 3625.31, 35.83),
	-- 	type = 'client',
	-- 	event = 'BL_CanhSat:cl:CheckListJob',
	-- 	label = 'Trò Chuyện Với Anh Nhân Viên',
	-- 	distance = 3.0,
	-- 	Job = 'police',
	-- },
	[3] = { --- CẤP XE
		name = 'nhan_vien_Cap_xe',
		coords = vector3(442.05, -1013.51, 28.62),
		type = 'client',
		event = 'BL_CanhSat:cl:CapXe',
		label = 'Trò Chuyện Với Cấp Xe',
		distance = 3.0,
		Job = 'police',
	},
	[4] = { --- CHUỘC XE
		name = 'nhan_vien_chuoc_xe',
		coords = vector3(459.04, -1017.06, 28.16),
		type = 'client',
		event = 'BL_Police:cl:OpenImpound',
		label = 'Trò Chuyện Với Chuộc Xe',
		distance = 3.0,
		Job = 'police',
	},
	[5] = { --- BẮT THỎ
		name = 'tuong_tac_bat_tho',
		coords = vector3(-2169.04, -519.189, 4.7201),
		type = 'client',
		event = 'BL_BatTho:cl:OpenTuongTac',
		label = 'Trò Chuyện với anh Nông Dân',
		distance = 3.0,
	},
	-- [6] = { --- BẮT THỎ
	-- 	name = 'thue_xe',
	-- 	coords = vector3(-277.144, -919.041, 32.267),
	-- 	type = 'client',
	-- 	event = 'BL_ThueXe:Cl:OpenMenu',
	-- 	label = 'Trò Chuyện với chị Thỏ Ngọc',
	-- 	distance = 3.0,
	-- },
	[7] = { --- BẮT ĐẦU NHIỆM VỤ RÃ XE
		name = 'ra_xe',
		coords = vector3(734.1173, -1294.90, 27.036),
		type = 'client',
		event = "BL_RaXe:client:StartChopShop",
		label = 'Trò Chuyện với khứa trộm xe',
		distance = 3.0,
	},
	-- [8] = { --- TOP THƯƠNG NHÂN
	-- 	name = 'top_thuong_nhan',
	-- 	coords = vector3(-228.013, -939.692, 32.246),
	-- 	type = 'client',
	-- 	event = "BL_TopThuongNhan:cl:OpenNUI",
	-- 	label = 'Kiểm Tra Top Thương Nhân',
	-- 	distance = 3.0,
	-- },
	[9] = { --- TRAO ĐỔI CẦN SA
		name = 'trao_doi_can_sa',
		coords = vector3(22.50687, -1217.96, 29.352),
		type = 'client',
		event = "BL_HaiCan:cl:TraoDoi",
		label = 'Trao Đổi Cần Sa',
		distance = 3.0,
	},
	[10] = { --- MỞ MENU XEM XE VÀ BÁN XE
		name = 'cardealer',
		coords = vector3(-2235.29, -390.86, 13.51),
		type = 'client',
		event = "BL_Cardealer:cl:OpenXemXe",
		label = 'Xem List Xe',
		distance = 3.0,
		Job = 'cardealer',
	},
	[11] = { --- MỞ MENU XEM XE VÀ BÁN XE
		name = 'cardealer',
		coords = vector3(-2237.67, -388.59, 13.52),
		type = 'client',
		event = "BL_Cardealer:cl:OpenNUI",
		label = 'Buôn Bán Xe',
		distance = 3.0,
		Job = 'cardealer',
	},
	[12] = { --- TRAO ĐỔI TRANG SỨC
		name = 'trao_doi_trang_suc',
		coords = vector3(-683.185, -172.963, 37.821),
		type = 'client',
		event = "BL_MocTui:cl:TraoDoiTrangSuc",
		label = 'Trao Đổi Trang Sức',
		distance = 3.0,
	},
	[13] = { --- TRAO ĐỔI TRANG SỨC
		name = 'trade_the_nha',
		coords = vector3(1495.217, 1115.870, 114.33),
		type = 'client',
		event = "BL_TromNha:cl:TradeTheNha",
		label = 'Trao Đổi Thẻ Nhà',
		distance = 3.0,
	},
	[14] = { --- TRAO ĐỔI TRANG SỨC
		name = 'trade_ban_do',
		coords = vector3(-217.540, -2373.14, 26.456),
		type = 'client',
		event = "BL_SuKienTet:cl:Trade_Manh_Kho_Bau",
		label = 'Trao Đổi Mảnh Kho Báu',
		distance = 3.0,
	},
	[15] = { --- TRAO ĐỔI TRANG SỨC
		name = 'trade_manh_ban',
		coords = vector3(1241.554, -3035.16, 9.3250),
		type = 'client',
		event = "BL_SuKienTet:cl:MuaManhKhoBau",
		label = 'Trao Đổi Mảnh Kho Báu Bẩn',
		distance = 3.0,
	},
	[16] = { --- TRAO ĐỔI TRANG SỨC
		name = 'ban_day_dong',
		coords =vector3(465.0748, -1512.68, 34.535),
		type = 'client',
		event = "BL_TromTruDien:cl:BanDayDong",
		label = 'Bán dây đồng',
		distance = 3.0,
	},
	[17] = { --- CẤP XE
		name = 'nhan_vien_Cap_xe1',
		coords = vector3(1730.28, 3633.89, 35.88),
		type = 'client',
		event = 'BL_CanhSat:cl:CapXe',
		label = 'Trò Chuyện Với Cấp Xe',
		distance = 3.0,
		Job = 'police',
	},
	[18] = { --- NHÂN VIÊN LỄ TÊN CẢNH SÁT
		name = 'le_tan_canh_sat',
		coords = vector3(441.10, -978.92, 30.69),
		type = 'client',
		event = 'BL_CanhSat:cl:CheckListJob',
		label = 'Trò Chuyện Với Anh Nhân Viên',
		distance = 3.0,
		Job = 'police',
	},
}

Config.DrawingTime = 20*1000 
Config.TextColor = {r=255, g=255,b=255} 

Config.waitTimeInSeconds = 5
Config.waitTime = Config.waitTimeInSeconds * 1000

Config.whitelistedJobs = {
	"police",
	"ttc",
	"ambulance",
	"admin"
}

Config.whitelistedJobs2 = {
	"ttc",
	"ambulance",
	"police",
	"admin"
}

Config.whitelistedJobs3 = {
	"police",
	"ambulance",
	"ttc",
	"admin"
}

Config.CitizenID_List = {
	"Bii Coding",
}

Config.Blacklist = {
    [GetHashKey("dodgeEMS")] = true,
    [GetHashKey("polpor")] = true,
}

Config.BlacklistPolice = {
    [GetHashKey("r1200rtp")] = true,
    [GetHashKey("sultanpoli")] = true,
	[GetHashKey("dodgeEMS")] = true,
    [GetHashKey("polpor")] = true,
}

Config.FlagsForBan = 5

Config.SuperJumpLength = 20.0

Config.MaxSpeed = 13

Config.Antiresourcestop = false

Config.IgnoredGroups = {
    ['mod'] = true,
    ['admin'] = true,
    ['god'] = true
}

Config.BlacklistedPlates = {
    "BRUTAN",
}

Config.BlacklistedEvents = {
    '211ef2f8-f09c-4582-91d8-087ca2130157',
    '265df2d8-421b-4727-b01d-b92fd6503f5e',
    '6a7af019-2b92-4ec2-9435-8fb9bd031c26',
    '8321hiue89js',
    '99kr-burglary:addMDFWMoney',
    'AdminMDFWMenu:giveCash',
    'AdminMeDFWMnu:giveBank',
    'adminmenu:allowall',
    'adminmenu:cashoutall',
    'AdminMenu:giveBank',
    'AdminMenu:giveCash',
    'AdminMenu:giveDirtyMDFWMoney',
    'AdminMenu:giveDirtyMoney',
    'adminmenu:setsalary',
    'advancedFuel:setEssence',
    'antilynx8:anticheat',
    'antilynx8r4a:anticheat',
    'antilynxr4:detect',
    'AntiLynxR4:kick',
    'AntiLynxR4:log',
    'antilynxr6:detection',
    'arisonarp:wiezienie',
    'Banca:dDFWMeposit',
    'Banca:deposit',
    'Banca:withdraw',
    'bank:depDFWMosit',
    'bank:tranDFWMsfer',
    'bank:withdDFWMraw',
    'BsCuff:Cuff696999',
    'BsCuff:Cuff696DFWM999',
    'c65a46c5-5485-4404-bacf-06a106900258',
    'CheckHandcDFWMuff',
    'CheckHandcuff',
    'cuffGDFWMranted',
    'cuffGranted',
    'cuffSeDFWMrver',
    'cuffServer',
    'DFWM:adminmenuenable',
    'DFWM:askAwake',
    'DFWM:checkup',
    'DFWM:cleanareaentity',
    'DFWM:cleanareapeds',
    'DFWM:cleanareaveh',
    'DFWM:enable',
    'DFWM:invalid',
    'DFWM:log',
    'DFWM:openmenu',
    'DFWM:spectate',
    'DFWM:ViolationDetected',
    'DiscordBot:plaDFWMyerDied',
    'DiscordBot:playerDied',
    'dmv:succeDFWMss',
    'dmv:success',
    'dqd36JWLRC72k8FDttZ5adUKwvwq9n9m',
    'eden_garage:payhealth',
    'ems:revive',
    'Esx-MenuPessoal:Boss_recruterplayer',
    'esx-qalle-hunting:DFWMreward',
    'esx-qalle-hunting:reward',
    'esx-qalle-hunting:seDFWMll',
    'esx-qalle-hunting:sell',
    'esx-qalle-jail:jailPDFWMlayer',
    'esx-qalle-jail:jailPlayer',
    'esx-qalle-jail:jailPlayerNew',
    'esx:clientLog',
    'esx:createMissingPickups',
    'esx:enterpolicecar',
    'esx:getSharedObject',
    'esx:getShDFWMaredObjDFWMect',
    'esx:giDFWMveInventoryItem',
    'esx:giveInventoryItem',
    'esx:onPickup',
    'esx:playerLoaded',
    'esx:removeInventoryItem',
    'esx:triggerServerCallback',
    'esx:updateLastPosition',
    'esx:updateLoadout',
    'esx:useItem',
    'esx_ambulancejob:reDFWMvive',
    'esx_ambulancejob:revive',
    'esx_ambulancejob:setDeathStatus',
    'esx_baDFWMnksecurity:pay',
    'esx_banksecurity:pay',
    'esx_biDFWMlling:sBill',
    'esx_billing:sBill',
    'esx_blackmoney:washMoney',
    'esx_blanchisDFWMseur:startWhitening',
    'esx_blanchisseur:startWhitening',
    'esx_blanchisseur:washMoney',
    'esx_carthDFWMief:pay',
    'esx_carthief:alertcoDFWMps',
    'esx_carthief:alertcops',
    'esx_carthief:pay',
    'esx_dmvschool:addLiceDFWMnse',
    'esx_dmvschool:addLicense',
    'esx_dmvschool:pay',
    'esx_dmvschool:pDFWMay',
    'esx_drugs:cancelProcessing',
    'esx_drugs:GetUserInventory',
    'esx_drugs:pickedUpCannabis',
    'esx_drugs:pickedUpCDFWMannabis',
    'esx_drugs:processCannabis',
    'esx_drugs:processCDFWMannabis',
    'esx_drugs:sellDrug',
    'esx_drugs:starDFWMtTransformOpium',
    'esx_drugs:startHarDFWMvestMeth',
    'esx_drugs:startHarvestCoke',
    'esx_drugs:startHarvestDFWMCoke',
    'esx_drugs:startHarvestMeth',
    'esx_drugs:startHarvestOpium',
    'esx_drugs:startHarvestWDFWMeed',
    'esx_drugs:startHarvestWeed',
    'esx_drugs:startHDFWMarvestOpium',
    'esx_drugs:startSellCDFWMoke',
    'esx_drugs:startSellCoke',
    'esx_drugs:startSellDFWMOpium',
    'esx_drugs:startSellMDFWMeth',
    'esx_drugs:startSellMeth',
    'esx_drugs:startSellOpium',
    'esx_drugs:startSellWeDFWMed',
    'esx_drugs:startSellWeed',
    'esx_drugs:startTDFWMransformMeth',
    'esx_drugs:startTransDFWMformCoke',
    'esx_drugs:startTransfoDFWMrmWeed',
    'esx_drugs:startTransformCoke',
    'esx_drugs:startTransformMeth',
    'esx_drugs:startTransformOpium',
    'esx_drugs:startTransformWeed',
    'esx_drugs:stopHarDFWMvestWeed',
    'esx_drugs:stopHarvDFWMestCoke',
    'esx_drugs:stopHarvesDFWMtMeth',
    'esx_drugs:stopHarvestCoke',
    'esx_drugs:stopHarvestDFWMOpium',
    'esx_drugs:stopHarvestMeth',
    'esx_drugs:stopHarvestOpium',
    'esx_drugs:stopHarvestWeed',
    'esx_drugs:stopSellCoke',
    'esx_drugs:stopSellDFWMCoke',
    'esx_drugs:stopSellMDFWMeth',
    'esx_drugs:stopSellMeth',
    'esx_drugs:stopSellOpiuDFWMm',
    'esx_drugs:stopSellOpium',
    'esx_drugs:stopSellWDFWMeed',
    'esx_drugs:stopSellWeed',
    'esx_drugs:stopTDFWMransformWeed',
    'esx_drugs:stopTranDFWMsformCoke',
    'esx_drugs:stopTranDFWMsformMeth',
    'esx_drugs:stopTransDFWMformOpium',
    'esx_drugs:stopTransformCoke',
    'esx_drugs:stopTransformMeth',
    'esx_drugs:stopTransformOpium',
    'esx_drugs:stopTransformWeed',
    'esx_fueldDFWMelivery:pay',
    'esx_fueldelivery:pay',
    'esx_garbageDFWMjob:pay',
    'esx_garbagejob:pay',
    'esx_goDFWMpostaljob:pay',
    'esx_godiDFWMrtyjob:pay',
    'esx_godirtyjob:pay',
    'esx_gopostaljob:pay',
    'esx_handcuffs:cufDFWMfing',
    'esx_handcuffs:cuffing',
    'esx_inventoryhud:openPlayerInventory',
    'esx_jaDFWMil:sToJail',
    'esx_jail:sToJail',
    'esx_jail:unjailQuest',
    'esx_jailer:sToJail',
    'esx_jailer:sToJailCatfrajerze',
    'esx_jailer:unjailTiDFWMme',
    'esx_jailer:unjailTime',
    'esx_jailler:sToJail',
    'esx_jDFWMailer:sToJail',
    'esx_jobs:caDFWMution',
    'esx_jobs:caution',
    'esx_jobs:startWork',
    'esx_jobs:stopWork',
    'esx_mafiajob:confiscateDFWMPlayerItem',
    'esx_mecanojob:onNPCJobCDFWMompleted',
    'esx_mecanojob:onNPCJobCompleted',
    'esx_mechanicjob:starDFWMtCraft',
    'esx_mechanicjob:startCraft',
    'esx_mechanicjob:startHarvest',
    'esx_moneywash:depoDFWMsit',
    'esx_moneywash:deposit',
    'esx_moneywash:witDFWMhdraw',
    'esx_moneywash:withdraw',
    'esx_pizza:pay',
    'esx_pizza:pDFWMay',
    'esx_policejob:haDFWMndcuff',
    'esx_policejob:handcuff',
    'esx_ranger:pay',
    'esx_ranger:pDFWMay',
    'esx_skin:openRestrictedMenu',
    'esx_skin:responseSaDFWMveSkin',
    'esx_skin:responseSaveSkin',
    'esx_sloDFWMtmachine:sv:2',
    'esx_slotmachine:sv:2',
    'esx_society:getOnlDFWMinePlayers',
    'esx_society:getOnlinePlayers',
    'esx_society:openBosDFWMsMenu',
    'esx_society:putVehicleDFWMInGarage',
    'esx_society:setJob',
    'esx_status:set',
    'esx_tankerjob:DFWMpay',
    'esx_truckDFWMerjob:pay',
    'esx_truckerjob:pay',
    'esx_vehicleshop:setVehicleOwned',
    'esx_vehicleshop:setVehicleOwnedDFWM',
    'esx_vehicleshop:setVehicleOwnedPlayerId',
    'esx_vehicletrunk:givDFWMeDirty',
    'esx_vehicletrunk:giveDirty',
    'f0ba1292-b68d-4d95-8823-6230cdf282b6',
    'gambling:sp',
    'gambling:speDFWMnd',
    'gcPhone:sMessage',
    'gcPhone:tchat_channel',
    'gcPhone:tchat_channelDFWM',
    'gcPhone:_internalAddMessage',
    'gcPhone:_internalAddMessageDFWM',
    'give_back',
    'h:xd',
    'HCheat:TempDisableDetDFWMection',
    'hentailover:xdlol',
    'JailUpdate',
    'js:jaDFWMiluser',
    'js:jailuser',
    'js:removejailtime',
    'laundry:washcash',
    'dt-fuel:PayFuDFWMel',
    'dt-fuel:PayFuel',
    'ljail:jailplayer',
    'lscustoms:payGarage',
    'lscustoms:pDFWMayGarage',
    'lscustoms:UpdateVeh',
    'lynx8:anticheat',
    'mellotrainer:adminKick',
    'mellotrainer:adminKickDFWM',
    'mellotrainer:adminTeDFWMmpBan',
    'mellotrainer:adminTempBan',
    'mellotrainer:s_adminKill',
    'MF_MobileMeth:RewardPlayers',
    'mission:completDFWMed',
    'mission:completed',
    'NB:destituerplayer',
    'NB:recDFWMruterplayer',
    'NB:recruterplayer',
    'OG_cuffs:cuffCheckNearest',
    'OG_cuffs:cuffCheckNeDFWMarest',
    'paramedic:revive',
    'paycheck:bonDFWMus',
    'paycheck:salary',
    'paycheck:salDFWMary',
    'police:cuffGDFWMranted',
    'police:cuffGranted',
    'program-keycard:hacking',
    'projektsantos:mandathajs',
    'Tem2LPs5Para5dCyjuHm87y2catFkMpV',
    'tost:zgarnijsiano',
    'tostzdrapka:wygranko',
    'truckerJob:succeDFWMss',
    'truckerJob:success',
    'uncuffGranted',
    'unCuffServer',
    'veh_SR:CheckMonDFWMeyForVeh',
    'vrp_slotmachDFWMine:server:2',
    'vrp_slotmachine:server:2',
    'whoapd:revive',
    'wojtek_ubereats:hajs',
    'wojtek_ubereats:napiwek',
    'wyspa_jail:jail',
    'wyspa_jail:jailPlayer',
    'xk3ly-barbasz:getfukingmony',
    'xk3ly-farmer:paycheck',
    'ynx8:anticheat',
}

Config.PolyChairs = {
	[1] = {
		coords = vector3(-1195.44, -883.55, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5,
	},
	[2] = {
		coords = vector3(-1194.96, -884.31, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[3] = {
		coords = vector3(-1193.82, -882.47, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[4] = {
		coords = vector3(-1193.30, -883.22, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[5] = {
		coords = vector3(-1192.98, -881.81, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[6] = {
		coords = vector3(-1192.48, -882.60, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[7] = {
		coords = vector3(-1191.01, -881.64, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[8] = {
		coords = vector3(-1191.52, -880.80, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[9] = {
		coords = vector3(-1189.33, -879.31, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[10] = {
		coords = vector3(-1189.85, -879.69, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[11] = {
		coords = vector3(-1188.14, -879.62, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[12] = {
		coords = vector3(-1187.72, -880.32, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[13] = {
		coords = vector3(-1187.08, -881.23, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[14] = {
		coords = vector3(-1187.89, -881.76, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[15] = {
		coords = vector3(-1185.99, -882.92, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[16] = {
		coords = vector3(-1186.81, -883.47, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[17] = {
		coords = vector3(-1183.18, -886.96, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[18] = {
		coords = vector3(-1183.96, -887.49, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[19] = {
		coords = vector3(-1182.06, -888.64, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[20] = {
		coords = vector3(-1182.87, -889.20, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[21] = {
		coords = vector3(-1180.97, -891.36, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[22] = {
		coords = vector3(-1181.82, -891.92, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[23] = {
		coords = vector3(-1181.00, -890.16, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[24] = {
		coords = vector3(-1181.41, -889.55, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[25] = {
		coords = vector3(-1183.94, -892.23, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[26] = {
		coords = vector3(-1183.43, -892.91, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[27] = {
		coords = vector3(-1184.89, -893.88, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[28] = {
		coords = vector3(-1185.38, -893.11, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[29] = {
		coords = vector3(-1185.72, -894.48, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[30] = {
		coords = vector3(-1186.22, -893.72, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[31] = {
		coords = vector3(-1187.37, -895.61, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[32] = {
		coords = vector3(-1187.89, -894.86, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[33] = {
		coords = vector3(-1191.19, -885.34, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[34] = {
		coords = vector3(-1190.86, -885.78, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[35] = {
		coords = vector3(-1191.12, -886.88, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[36] = {
		coords = vector3(-1191.76, -887.33, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[37] = {
		coords = vector3(-1192.77, -887.12, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[38] = {
		coords = vector3(-1193.15, -886.60, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[39] = {
		coords = vector3(-1189.26, -892.31, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[40] = {
		coords = vector3(-1189.65, -891.76, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[41] = {
		coords = vector3(-1189.37, -890.67, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[42] = {
		coords = vector3(-1188.82, -890.28, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[43] = {
		coords = vector3(-1187.85, -890.23, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[44] = {
		coords = vector3(-1187.50, -890.74, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[45] = {
		coords = vector3(-1193.91, -887.50, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[46] = {
		coords = vector3(-1192.99, -888.86, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[47] = {
		coords = vector3(-1191.30, -891.31, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[48] = {
		coords = vector3(-1190.44, -892.68, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[49] = {
		coords = vector3(-1188.91, -896.76, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[50] = {
		coords = vector3(-1189.62, -897.21, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[51] = {
		coords = vector3(-1190.85, -897.04, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[52] = {
		coords = vector3(-1191.33, -896.33, 14.0),
		heading = 303.0,
		length = 0.6,
		width = 0.6,
		minZ = 13.0,
		maxZ = 14.2,
		zOffset = -0.5
	},
	[53] = {
		coords = vector3(-1200.55, -887.10, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[54] = {
		coords = vector3(-1203.02, -888.78, 14.0),
		heading = 213.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.99,
		maxZ = 14.19,
		zOffset = -0.5
	},
	[55] = {
		coords = vector3(-1180.80, -900.72, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.99,
		maxZ = 14.19,
		zOffset = -0.5
	},
	[56] = {
		coords = vector3(-1185.43, -904.10, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.55
	},
	[57] = {
		coords = vector3(-1184.68, -903.58, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.55
	},
	[58] = {
		coords = vector3(-1188.82, -903.77, 14.0),
		heading = 330.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[59] = {
		coords = vector3(-1187.79, -901.57, 14.0),
		heading = 309.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[60] = {
		coords = vector3(-1188.45, -900.58, 14.0),
		heading = 289.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[61] = {
		coords = vector3(-1186.65, -899.34, 14.0),
		heading = 199.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[62] = {
		coords = vector3(-1177.39, -895.82, 14.0),
		heading = 123.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[63] = {
		coords = vector3(-1179.68, -896.44, 14.0),
		heading = 294.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[64] = {
		coords = vector3(-1178.90, -897.46, 14.0),
		heading = 324.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.5
	},
	[65] = {
		coords = vector3(-1177.84, -899.15, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.55
	},
	[66] = {
		coords = vector3(-1177.11, -898.76, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.55
	},
	[67] = {
		coords = vector3(-1176.38, -898.29, 14.0),
		heading = 33.0,
		length = 0.6,
		width = 0.6,
		minZ = 12.98,
		maxZ = 14.18,
		zOffset = -0.55
	},
}

Config.Props = {
	"prop_bench_01a",
	"prop_bench_01b",
	"prop_bench_01c",
	"prop_bench_02",
	"prop_bench_03",
	"prop_bench_04",
	"prop_bench_05",
	"prop_bench_06",
	"xm_lab_chairarm_02",
	"prop_bench_05",
	"prop_bench_08",
	"prop_bench_09",
	"prop_bench_10",
	"prop_bench_11",
	"prop_fib_3b_bench",
	"prop_ld_bench01",
	"prop_wait_bench_01",
	"hei_prop_heist_off_chair",
	"v_res_fh_dineeamesa",
	"v_res_fh_dineeamesb",
	"hei_prop_hei_skid_chair",
	"kachal_kk_barrelchair",
	"prop_chair_01a",
	"prop_chair_01b",
	"prop_chair_02",
	"prop_chair_03",
	"prop_chair_04a",
	"prop_chair_04b",
	"prop_chair_05",
	"prop_chair_06",
	"prop_chair_05",
	"prop_chair_08",
	"prop_chair_09",
	"prop_chair_10",
	"prop_chateau_chair_01",
	"prop_clown_chair",
	"prop_cs_office_chair",
	"prop_direct_chair_01",
	"prop_direct_chair_02",
	"prop_gc_chair02",
	"prop_off_chair_01",
	"prop_off_chair_03",
	"prop_off_chair_04",
	"prop_off_chair_04b",
	"prop_off_chair_04_s",
	"prop_off_chair_05",
	"prop_old_deck_chair",
	"prop_old_wood_chair",
	"prop_rock_chair_01",
	"prop_skid_chair_01",
	"prop_skid_chair_02",
	"prop_skid_chair_03",
	"prop_sol_chair",
	"prop_wheelchair_01",
	"prop_wheelchair_01_s",
	"p_armchair_01_s",
	"p_clb_officechair_s",
	"p_dinechair_01_s",
	"p_ilev_p_easychair_s",
	"p_soloffchair_s",
	"p_yacht_chair_01_s",
	"v_club_officechair",
	"v_corp_bk_chair3",
	"v_corp_cd_chair",
	"v_corp_offchair",
	"v_ilev_chair02_ped",
	"v_ilev_hd_chair",
	"v_ilev_p_easychair",
	"v_ret_gc_chair03",
	"prop_ld_farm_chair01",
	"prop_table_04_chr",
	"prop_table_05_chr",
	"prop_table_06_chr",
	"v_ilev_leath_chr",
	"prop_table_01_chr_a",
	"prop_table_01_chr_b",
	"prop_table_02_chr",
	"prop_table_03b_chr",
	"prop_table_03_chr",
	"prop_torture_ch_01",
	"v_ilev_fh_dineeamesa",
	"v_ilev_fh_kitchenstool",
	"v_ilev_tort_stool",
	"v_ilev_fh_kitchenstool",
	"v_ilev_fh_kitchenstool",
	"v_ilev_fh_kitchenstool",
	"v_ilev_fh_kitchenstool",
	"hei_prop_yah_seat_01",
	"hei_prop_yah_seat_02",
	"hei_prop_yah_seat_03",
	"prop_waiting_seat_01",
	"prop_yacht_seat_01",
	"prop_yacht_seat_02",
	"prop_yacht_seat_03",
	"prop_hobo_seat_01",
	"prop_rub_couch01",
	"miss_rub_couch_01",
	"prop_ld_farm_couch01",
	"prop_ld_farm_couch02",
	"prop_rub_couch02",
	"prop_rub_couch03",
	"prop_rub_couch04",
	"p_lev_sofa_s",
	"p_res_sofa_l_s",
	"p_v_med_p_sofa_s",
	"p_yacht_sofa_01_s",
	"v_ilev_m_sofa",
	"v_res_tre_sofa_s",
	"v_tre_sofa_mess_a_s",
	"v_tre_sofa_mess_b_s",
	"v_tre_sofa_mess_c_s",
	"prop_roller_car_01",
	"prop_roller_car_02",
}

Config.Sitable = {
	--Only verticalOffset works right now!	
	--all scenarios: pastebin.com/6mrYTdQv
	
	-- BENCH
	prop_bench_01a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_01b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_01c 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_03 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_04 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_05 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_06 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_07 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_08 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_09 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_10 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_11 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_fib_3b_bench 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_bench01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wait_bench_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- CHAIR
	hane_coolbeans_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_res_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_res_fh_dineeamesb 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	kachal_kk_barrelchair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_08_chr 		    = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	uniqx_burgershot_seating01 	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_heist_off_chair 	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_hei_skid_chair 	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_01a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_01b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_03 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_04a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_04b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_05 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_06 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_07 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	xm_lab_chairarm_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_08 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_09 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_10 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chateau_chair_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_clown_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_cs_office_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_direct_chair_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_direct_chair_02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_gc_chair02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04b 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_05 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_old_deck_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_old_wood_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rock_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_sol_chair 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wheelchair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wheelchair_01_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_armchair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_clb_officechair_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_dinechair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_ilev_p_easychair_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_soloffchair_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_yacht_chair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_club_officechair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_bk_chair3 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_cd_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_offchair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_chair02_ped 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_hd_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_p_easychair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ret_gc_chair03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_chair01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_04_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_05_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_06_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_leath_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_01_chr_a 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_01_chr_b 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_02_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_03b_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_03_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_torture_ch_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },


	v_ilev_fh_kitchenstool 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_tort_stool 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- SEAT
	hei_prop_yah_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_yah_seat_02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_yah_seat_03 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_waiting_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_hobo_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.65, forwardOffset = 0.0, leftOffset = 0.0 },

	-- COUCH
	prop_rub_couch01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	miss_rub_couch_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_couch01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_couch02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch04 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- SOFA
	p_lev_sofa_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_res_sofa_l_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_v_med_p_sofa_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_yacht_sofa_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_m_sofa 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_res_tre_sofa_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_a_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_b_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_c_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- MISC
	prop_roller_car_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_roller_car_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
}

return Config